FROM golang:1.6

RUN go get -u github.com/tools/godep
RUN go get -u github.com/golang/lint/golint

COPY ./ "$GOPATH/src/github.com/mesosphere/mesos-dns"

# Only update dependencies if we are not using godep
RUN cd "$GOPATH/src/github.com/mesosphere/mesos-dns" && ( test -d ./Godeps || echo go get -u )

# Install consul for tests
RUN go get -u github.com/hashicorp/consul

WORKDIR "$GOPATH/src/github.com/mesosphere/mesos-dns"
